# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\_RD\studio100Paris\s100_Vic\debug\Studio100\Studio100Tools\PrevizTools\forestGenerator\Ui_forestGenerator.ui'
#
# Created: Wed Mar 06 13:56:49 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_forestGenerator(object):
    def setupUi(self, forestGenerator):
        forestGenerator.setObjectName("forestGenerator")
        forestGenerator.resize(356, 816)
        self.verticalLayout = QtGui.QVBoxLayout(forestGenerator)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.surface_gb = QtGui.QGroupBox(forestGenerator)
        self.surface_gb.setFlat(False)
        self.surface_gb.setCheckable(False)
        self.surface_gb.setObjectName("surface_gb")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.surface_gb)
        self.verticalLayout_2.setContentsMargins(6, 2, 2, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.surfaceSelect_bt = QtGui.QPushButton(self.surface_gb)
        self.surfaceSelect_bt.setObjectName("surfaceSelect_bt")
        self.verticalLayout_2.addWidget(self.surfaceSelect_bt)
        self.surfaceInfo_le = QtGui.QLineEdit(self.surface_gb)
        self.surfaceInfo_le.setEnabled(False)
        self.surfaceInfo_le.setObjectName("surfaceInfo_le")
        self.verticalLayout_2.addWidget(self.surfaceInfo_le)
        self.surfaceSmooth_cb = QtGui.QCheckBox(self.surface_gb)
        self.surfaceSmooth_cb.setObjectName("surfaceSmooth_cb")
        self.verticalLayout_2.addWidget(self.surfaceSmooth_cb)
        self.verticalLayout.addWidget(self.surface_gb)
        self.instance_gb = QtGui.QGroupBox(forestGenerator)
        self.instance_gb.setFlat(True)
        self.instance_gb.setCheckable(False)
        self.instance_gb.setObjectName("instance_gb")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.instance_gb)
        self.verticalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.instanceAdd_bt = QtGui.QPushButton(self.instance_gb)
        self.instanceAdd_bt.setObjectName("instanceAdd_bt")
        self.horizontalLayout.addWidget(self.instanceAdd_bt)
        self.instanceRemoveSel_bt = QtGui.QPushButton(self.instance_gb)
        self.instanceRemoveSel_bt.setObjectName("instanceRemoveSel_bt")
        self.horizontalLayout.addWidget(self.instanceRemoveSel_bt)
        self.instanceClear_bt = QtGui.QPushButton(self.instance_gb)
        self.instanceClear_bt.setObjectName("instanceClear_bt")
        self.horizontalLayout.addWidget(self.instanceClear_bt)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.instance_tw = QtGui.QTableWidget(self.instance_gb)
        self.instance_tw.setObjectName("instance_tw")
        self.instance_tw.setColumnCount(0)
        self.instance_tw.setRowCount(0)
        self.verticalLayout_3.addWidget(self.instance_tw)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtGui.QSpacerItem(280, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.globalScale_lb = QtGui.QLabel(self.instance_gb)
        self.globalScale_lb.setObjectName("globalScale_lb")
        self.horizontalLayout_6.addWidget(self.globalScale_lb)
        self.globalScale_le = QtGui.QLineEdit(self.instance_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalScale_le.sizePolicy().hasHeightForWidth())
        self.globalScale_le.setSizePolicy(sizePolicy)
        self.globalScale_le.setMinimumSize(QtCore.QSize(0, 0))
        self.globalScale_le.setSizeIncrement(QtCore.QSize(0, 0))
        self.globalScale_le.setBaseSize(QtCore.QSize(0, 0))
        self.globalScale_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.globalScale_le.setObjectName("globalScale_le")
        self.horizontalLayout_6.addWidget(self.globalScale_le)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.global_gb = QtGui.QGroupBox(self.instance_gb)
        self.global_gb.setFlat(True)
        self.global_gb.setCheckable(True)
        self.global_gb.setChecked(False)
        self.global_gb.setObjectName("global_gb")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.global_gb)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.global_qw = QtGui.QWidget(self.global_gb)
        self.global_qw.setEnabled(False)
        self.global_qw.setObjectName("global_qw")
        self.global_lt = QtGui.QVBoxLayout(self.global_qw)
        self.global_lt.setSpacing(1)
        self.global_lt.setContentsMargins(0, 0, 0, 0)
        self.global_lt.setObjectName("global_lt")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.globalRotate_lb = QtGui.QLabel(self.global_qw)
        self.globalRotate_lb.setMinimumSize(QtCore.QSize(75, 0))
        self.globalRotate_lb.setObjectName("globalRotate_lb")
        self.horizontalLayout_4.addWidget(self.globalRotate_lb)
        self.globalRotateX_le = QtGui.QLineEdit(self.global_qw)
        self.globalRotateX_le.setObjectName("globalRotateX_le")
        self.horizontalLayout_4.addWidget(self.globalRotateX_le)
        self.globalRotateY_le = QtGui.QLineEdit(self.global_qw)
        self.globalRotateY_le.setObjectName("globalRotateY_le")
        self.horizontalLayout_4.addWidget(self.globalRotateY_le)
        self.globalRotateZ_le = QtGui.QLineEdit(self.global_qw)
        self.globalRotateZ_le.setObjectName("globalRotateZ_le")
        self.horizontalLayout_4.addWidget(self.globalRotateZ_le)
        self.global_lt.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.globalRadius_lb = QtGui.QLabel(self.global_qw)
        self.globalRadius_lb.setMinimumSize(QtCore.QSize(75, 0))
        self.globalRadius_lb.setObjectName("globalRadius_lb")
        self.horizontalLayout_3.addWidget(self.globalRadius_lb)
        self.globalRadius_le = QtGui.QLineEdit(self.global_qw)
        self.globalRadius_le.setMinimumSize(QtCore.QSize(0, 0))
        self.globalRadius_le.setObjectName("globalRadius_le")
        self.horizontalLayout_3.addWidget(self.globalRadius_le)
        self.global_lt.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.globalScaleMin_lb = QtGui.QLabel(self.global_qw)
        self.globalScaleMin_lb.setMinimumSize(QtCore.QSize(75, 0))
        self.globalScaleMin_lb.setObjectName("globalScaleMin_lb")
        self.horizontalLayout_2.addWidget(self.globalScaleMin_lb)
        self.globalScaleMin_le = QtGui.QLineEdit(self.global_qw)
        self.globalScaleMin_le.setObjectName("globalScaleMin_le")
        self.horizontalLayout_2.addWidget(self.globalScaleMin_le)
        self.globalScaleMax_lb = QtGui.QLabel(self.global_qw)
        self.globalScaleMax_lb.setObjectName("globalScaleMax_lb")
        self.horizontalLayout_2.addWidget(self.globalScaleMax_lb)
        self.globalScaleMax_le = QtGui.QLineEdit(self.global_qw)
        self.globalScaleMax_le.setObjectName("globalScaleMax_le")
        self.horizontalLayout_2.addWidget(self.globalScaleMax_le)
        self.global_lt.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.global_qw)
        self.verticalLayout_3.addWidget(self.global_gb)
        self.verticalLayout.addWidget(self.instance_gb)
        self.simulation_gb = QtGui.QGroupBox(forestGenerator)
        self.simulation_gb.setFlat(True)
        self.simulation_gb.setObjectName("simulation_gb")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.simulation_gb)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.simulationEmit_lb = QtGui.QLabel(self.simulation_gb)
        self.simulationEmit_lb.setObjectName("simulationEmit_lb")
        self.horizontalLayout_10.addWidget(self.simulationEmit_lb)
        self.simulationEmit_le = QtGui.QLineEdit(self.simulation_gb)
        self.simulationEmit_le.setObjectName("simulationEmit_le")
        self.horizontalLayout_10.addWidget(self.simulationEmit_le)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.simulationAge_lb = QtGui.QLabel(self.simulation_gb)
        self.simulationAge_lb.setObjectName("simulationAge_lb")
        self.horizontalLayout_9.addWidget(self.simulationAge_lb)
        self.simulationAge_le = QtGui.QLineEdit(self.simulation_gb)
        self.simulationAge_le.setObjectName("simulationAge_le")
        self.horizontalLayout_9.addWidget(self.simulationAge_le)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.simulation_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 0))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.simulationlarge_cb = QtGui.QCheckBox(self.simulation_gb)
        self.simulationlarge_cb.setChecked(True)
        self.simulationlarge_cb.setObjectName("simulationlarge_cb")
        self.verticalLayout_6.addWidget(self.simulationlarge_cb)
        self.simulationMedium_cb = QtGui.QCheckBox(self.simulation_gb)
        self.simulationMedium_cb.setChecked(True)
        self.simulationMedium_cb.setObjectName("simulationMedium_cb")
        self.verticalLayout_6.addWidget(self.simulationMedium_cb)
        self.simulationSmall_cb = QtGui.QCheckBox(self.simulation_gb)
        self.simulationSmall_cb.setChecked(True)
        self.simulationSmall_cb.setObjectName("simulationSmall_cb")
        self.verticalLayout_6.addWidget(self.simulationSmall_cb)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.simulationContinue_bt = QtGui.QPushButton(self.simulation_gb)
        self.simulationContinue_bt.setObjectName("simulationContinue_bt")
        self.horizontalLayout_5.addWidget(self.simulationContinue_bt)
        self.simulationStart_bt = QtGui.QPushButton(self.simulation_gb)
        self.simulationStart_bt.setObjectName("simulationStart_bt")
        self.horizontalLayout_5.addWidget(self.simulationStart_bt)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.groupBox = QtGui.QGroupBox(self.simulation_gb)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.simulationDisplayRadius_cb = QtGui.QCheckBox(self.groupBox)
        self.simulationDisplayRadius_cb.setObjectName("simulationDisplayRadius_cb")
        self.verticalLayout_5.addWidget(self.simulationDisplayRadius_cb)
        self.simulationDisplayInstance_cb = QtGui.QCheckBox(self.groupBox)
        self.simulationDisplayInstance_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.simulationDisplayInstance_cb.setChecked(True)
        self.simulationDisplayInstance_cb.setObjectName("simulationDisplayInstance_cb")
        self.verticalLayout_5.addWidget(self.simulationDisplayInstance_cb)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.updateRadius_gb = QtGui.QGroupBox(self.simulation_gb)
        self.updateRadius_gb.setObjectName("updateRadius_gb")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.updateRadius_gb)
        self.verticalLayout_9.setContentsMargins(2, 6, 2, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.updateRadiusOp_cb = QtGui.QComboBox(self.updateRadius_gb)
        self.updateRadiusOp_cb.setObjectName("updateRadiusOp_cb")
        self.updateRadiusOp_cb.addItem("")
        self.updateRadiusOp_cb.addItem("")
        self.horizontalLayout_12.addWidget(self.updateRadiusOp_cb)
        self.updateRadiusBy_lb = QtGui.QLabel(self.updateRadius_gb)
        self.updateRadiusBy_lb.setObjectName("updateRadiusBy_lb")
        self.horizontalLayout_12.addWidget(self.updateRadiusBy_lb)
        self.updateRadiusBy_le = QtGui.QLineEdit(self.updateRadius_gb)
        self.updateRadiusBy_le.setObjectName("updateRadiusBy_le")
        self.horizontalLayout_12.addWidget(self.updateRadiusBy_le)
        self.updateRadiusType_lb = QtGui.QLabel(self.updateRadius_gb)
        self.updateRadiusType_lb.setObjectName("updateRadiusType_lb")
        self.horizontalLayout_12.addWidget(self.updateRadiusType_lb)
        self.updateRadiusType_cb = QtGui.QComboBox(self.updateRadius_gb)
        self.updateRadiusType_cb.setObjectName("updateRadiusType_cb")
        self.updateRadiusType_cb.addItem("")
        self.updateRadiusType_cb.addItem("")
        self.updateRadiusType_cb.addItem("")
        self.horizontalLayout_12.addWidget(self.updateRadiusType_cb)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.updateRadius_bt = QtGui.QPushButton(self.updateRadius_gb)
        self.updateRadius_bt.setObjectName("updateRadius_bt")
        self.verticalLayout_9.addWidget(self.updateRadius_bt)
        self.verticalLayout_8.addWidget(self.updateRadius_gb)
        self.verticalLayout.addWidget(self.simulation_gb)
        self.line = QtGui.QFrame(forestGenerator)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.stop_bt = QtGui.QPushButton(forestGenerator)
        self.stop_bt.setMinimumSize(QtCore.QSize(0, 50))
        self.stop_bt.setDefault(False)
        self.stop_bt.setFlat(False)
        self.stop_bt.setObjectName("stop_bt")
        self.verticalLayout.addWidget(self.stop_bt)
        self.line_2 = QtGui.QFrame(forestGenerator)
        self.line_2.setMidLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.bake_qw = QtGui.QWidget(forestGenerator)
        self.bake_qw.setObjectName("bake_qw")
        self.bake_lt = QtGui.QVBoxLayout(self.bake_qw)
        self.bake_lt.setContentsMargins(0, 0, 0, 0)
        self.bake_lt.setContentsMargins(0, 0, 0, 0)
        self.bake_lt.setObjectName("bake_lt")
        self.bake_gb = QtGui.QGroupBox(self.bake_qw)
        self.bake_gb.setFlat(True)
        self.bake_gb.setObjectName("bake_gb")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.bake_gb)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bakeType_cmb = QtGui.QComboBox(self.bake_gb)
        self.bakeType_cmb.setObjectName("bakeType_cmb")
        self.bakeType_cmb.addItem("")
        self.bakeType_cmb.addItem("")
        self.bakeType_cmb.addItem("")
        self.horizontalLayout_7.addWidget(self.bakeType_cmb)
        self.bakeKeepRotate_cb = QtGui.QCheckBox(self.bake_gb)
        self.bakeKeepRotate_cb.setChecked(True)
        self.bakeKeepRotate_cb.setObjectName("bakeKeepRotate_cb")
        self.horizontalLayout_7.addWidget(self.bakeKeepRotate_cb)
        self.bakeKeepScale_cb = QtGui.QCheckBox(self.bake_gb)
        self.bakeKeepScale_cb.setChecked(True)
        self.bakeKeepScale_cb.setObjectName("bakeKeepScale_cb")
        self.horizontalLayout_7.addWidget(self.bakeKeepScale_cb)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.bake_lt.addWidget(self.bake_gb)
        self.bake_bn = QtGui.QPushButton(self.bake_qw)
        self.bake_bn.setMinimumSize(QtCore.QSize(0, 50))
        self.bake_bn.setObjectName("bake_bn")
        self.bake_lt.addWidget(self.bake_bn)
        self.verticalLayout.addWidget(self.bake_qw)

        self.retranslateUi(forestGenerator)
        self.updateRadiusType_cb.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(forestGenerator)

    def retranslateUi(self, forestGenerator):
        forestGenerator.setWindowTitle(QtGui.QApplication.translate("forestGenerator", "Forest generator", None, QtGui.QApplication.UnicodeUTF8))
        self.surface_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "1 - Surface to cover", None, QtGui.QApplication.UnicodeUTF8))
        self.surfaceSelect_bt.setText(QtGui.QApplication.translate("forestGenerator", "Select Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.surfaceSmooth_cb.setText(QtGui.QApplication.translate("forestGenerator", "Smooth surface", None, QtGui.QApplication.UnicodeUTF8))
        self.instance_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "2 - Instances to populate", None, QtGui.QApplication.UnicodeUTF8))
        self.instanceAdd_bt.setText(QtGui.QApplication.translate("forestGenerator", "ADD", None, QtGui.QApplication.UnicodeUTF8))
        self.instanceRemoveSel_bt.setText(QtGui.QApplication.translate("forestGenerator", "REMOVE SEL.", None, QtGui.QApplication.UnicodeUTF8))
        self.instanceClear_bt.setText(QtGui.QApplication.translate("forestGenerator", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.globalScale_lb.setText(QtGui.QApplication.translate("forestGenerator", "Global Scale :", None, QtGui.QApplication.UnicodeUTF8))
        self.globalScale_le.setText(QtGui.QApplication.translate("forestGenerator", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.global_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "Override specific parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.globalRotate_lb.setText(QtGui.QApplication.translate("forestGenerator", "Rotate range :", None, QtGui.QApplication.UnicodeUTF8))
        self.globalRadius_lb.setText(QtGui.QApplication.translate("forestGenerator", "Radius :", None, QtGui.QApplication.UnicodeUTF8))
        self.globalScaleMin_lb.setText(QtGui.QApplication.translate("forestGenerator", "Scale min :", None, QtGui.QApplication.UnicodeUTF8))
        self.globalScaleMax_lb.setText(QtGui.QApplication.translate("forestGenerator", "Scale max :", None, QtGui.QApplication.UnicodeUTF8))
        self.simulation_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "3 - Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationEmit_lb.setText(QtGui.QApplication.translate("forestGenerator", "Emit part :", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationEmit_le.setText(QtGui.QApplication.translate("forestGenerator", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationAge_lb.setText(QtGui.QApplication.translate("forestGenerator", "Age kill Particle :", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationAge_le.setText(QtGui.QApplication.translate("forestGenerator", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("forestGenerator", "Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationlarge_cb.setText(QtGui.QApplication.translate("forestGenerator", "Large", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationMedium_cb.setText(QtGui.QApplication.translate("forestGenerator", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationSmall_cb.setText(QtGui.QApplication.translate("forestGenerator", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationContinue_bt.setText(QtGui.QApplication.translate("forestGenerator", "CONTINUE", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationStart_bt.setText(QtGui.QApplication.translate("forestGenerator", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("forestGenerator", "Display :", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationDisplayRadius_cb.setText(QtGui.QApplication.translate("forestGenerator", "Radius Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationDisplayInstance_cb.setText(QtGui.QApplication.translate("forestGenerator", "Instance Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadius_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "Update Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusOp_cb.setItemText(0, QtGui.QApplication.translate("forestGenerator", "Divide", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusOp_cb.setItemText(1, QtGui.QApplication.translate("forestGenerator", "Multiply", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusBy_lb.setText(QtGui.QApplication.translate("forestGenerator", "radius by", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusType_lb.setText(QtGui.QApplication.translate("forestGenerator", "Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusType_cb.setItemText(0, QtGui.QApplication.translate("forestGenerator", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusType_cb.setItemText(1, QtGui.QApplication.translate("forestGenerator", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadiusType_cb.setItemText(2, QtGui.QApplication.translate("forestGenerator", "Large", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRadius_bt.setText(QtGui.QApplication.translate("forestGenerator", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_bt.setText(QtGui.QApplication.translate("forestGenerator", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.bake_gb.setTitle(QtGui.QApplication.translate("forestGenerator", "4 -  Bake", None, QtGui.QApplication.UnicodeUTF8))
        self.bakeType_cmb.setItemText(0, QtGui.QApplication.translate("forestGenerator", "Dupl. with Instance", None, QtGui.QApplication.UnicodeUTF8))
        self.bakeType_cmb.setItemText(1, QtGui.QApplication.translate("forestGenerator", "Dupl. with Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.bakeType_cmb.setItemText(2, QtGui.QApplication.translate("forestGenerator", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.bakeKeepRotate_cb.setText(QtGui.QApplication.translate("forestGenerator", "keep Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.bakeKeepScale_cb.setText(QtGui.QApplication.translate("forestGenerator", "keep Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.bake_bn.setText(QtGui.QApplication.translate("forestGenerator", "CLEANUP and BAKE", None, QtGui.QApplication.UnicodeUTF8))

